[tool.poetry]
name = "pizza-delivery-api"
version = "0.1.0"
description = ""
authors = ["uneku"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.109.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
